config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, length: { minimum: 10 }
  validates :content, length: { in: 10..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      redirect_to(action: :index)
    else
      flash.now[:error] = "Give 10 letters title and min 10 letters content"
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    @article.title = params[:article][:title]
    @article.content = params[:article][:content]

    if @article.save
      redirect_to(action: :index)
    else
      flash.now[:error] = "Please give at least 10 letters for Title and 10 letters for Content"
      render :new
    end
  end

  def destroy

    Article.delete(params[:id])
    redirect_to(action: :index)
  end

  def index
    @articles = Article.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label(:title) %><br>
    <%= f.text_field(:title) %>
  </p>

  <p>
    <%= f.label(:content) %><br>
    <%= f.text_area(:content) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <p>
    <%= article.title + ": " + article.content %>
    <%= form_for(article, method: :delete) do |f| %>
      <%= f.submit :Delete %>
      <%= link_to('Edit Article', edit_article_path(article)) %>
    <% end %>

  </p>


<% end %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label(:title) %><br>
    <%= f.text_field(:title) %>
  </p>

  <p>
    <%= f.label(:content) %><br>
    <%= f.text_area(:content) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= link_to('Edit Article', edit_article_path) %>
<%= link_to('Return to articles', articles_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h1>Hello world!<h1>
  